# STRING - characters that are wrapped within quotes.
# characters can be letters, numbers, and symbols.
# you can use both single and double quotation
# marks for string.

'Kobe Bryant'

'123 Main street'

'This cost $100 dollars'

# the hastag is a marker that makes anything written
# behind it invisible to the computer.

# INTEGERS - datatypes that are just whole numbers, or numbers
# without a decimal point. 
# we dont have to add any special symbols. we can write the number
# as is. 

10

20

2000000

# FLOATS- A number with a decimal. 

20.99

3.339

0.232


# BOOLEAN- a data type that can only be either true or false
# we do not use quotation marks for boolean values. the computer 
# understand these words as something unique.

False

True








"Ian Kimble" 

"123 main street"

"this costs $10.00"